spring.application.name=portfolio

spring.datasource.url=jdbc:postgresql://localhost:5432/portfolio
spring.datasource.username=postgres
spring.datasource.password=Murphy10

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true